### ISSUE TITLE
Is there a way to make row customizing methods work with this package?

### ISSUE THREAD

**Issue by OzanKurt** [yajra/laravel-datatables-fractal#22]
https://yajrabox.com/docs/laravel-datatables/master/response-fractal

> When using tranformer, all response manipulations must be done via transformer. Thus `addColumn`, `editColumn`, `removeColumn`, `setRowAttr`,`setClassAttr`, etc... should be avoided when using fractal.

https://yajrabox.com/docs/laravel-datatables/master/row-options

The methods above are extremely useful, why is fractal preventing their use?

**Comment by benyaminl** [comment]
> https://yajrabox.com/docs/laravel-datatables/master/response-fractal
> 
> > When using tranformer, all response manipulations must be done via transformer. Thus `addColumn`, `editColumn`, `removeColumn`, `setRowAttr`,`setClassAttr`, etc... should be avoided when using fractal.
> 
> https://yajrabox.com/docs/laravel-datatables/master/row-options
> 
> The methods above are extremely useful, why is fractal preventing their use?

Because with fractal it self you can return data on each row, than what's the point of adding columns with add Column or remove Column if you can change using fractal manually on the laravel transformer? 

Last time I also think I want to add Column but after learn about it's change the return as free as I want, I left addColumn if not needed.
